on:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - 'master'
    tags:
      - 'v*'

# Secrets:
# * CACHE_VERSION - Set to `date +%s`, set new when the cache should be busted

env:
  BUILD_EMBEDDED: true
  DIALYZER_PLT_PRIV: true
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:

  format:
    name: Check Formatting
    
    runs-on: ubuntu-latest

    env:
      MIX_ENV: dev

    strategy:
      fail-fast: false
      matrix:
        otp: [24.1.1]
        elixir: [1.12.3]

    steps:
      - uses: actions/checkout@v2
      - uses: erlef/setup-elixir@v1
        with:
          otp-version: ${{matrix.otp}}
          elixir-version: ${{matrix.elixir}}
      - uses: actions/cache@v2
        with:
          path: deps
          key: deps-${{ secrets.CACHE_VERSION }}-${{matrix.otp}}-${{matrix.elixir}}-${{ runner.os }}-${{ hashFiles('mix.lock') }}
          restore-keys: |
            deps-${{ secrets.CACHE_VERSION }}-${{matrix.otp}}-${{matrix.elixir}}-${{ runner.os }}-
            deps-${{ secrets.CACHE_VERSION }}-${{matrix.otp}}-${{matrix.elixir}}-
      - run: mix deps.get
      - run: mix format --check-formatted

  test:
    name: Run Tests & Submit Coverage

    runs-on: ubuntu-latest

    env:
      MIX_ENV: test

    strategy:
      fail-fast: false
      matrix:
        otp: [21.3, 22.3, 23.3, 24.1.1]
        elixir: [1.8.2, 1.9.4, 1.10.4, 1.11.4, 1.12.3]
        exclude:
          - otp: 21.3
            elixir: 1.12.3
          - otp: 24.1.1
            elixir: 1.8.2
          - otp: 24.1.1
            elixir: 1.9.4

    steps:
      - uses: actions/checkout@v2
      - uses: erlef/setup-elixir@v1
        with:
          otp-version: ${{matrix.otp}}
          elixir-version: ${{matrix.elixir}}
      - uses: actions/cache@v2
        with:
          path: deps
          key: deps-${{ secrets.CACHE_VERSION }}-${{matrix.otp}}-${{matrix.elixir}}-${{ runner.os }}-${{ hashFiles('mix.lock') }}
          restore-keys: |
            deps-${{ secrets.CACHE_VERSION }}-${{matrix.otp}}-${{matrix.elixir}}-${{ runner.os }}-
            deps-${{ secrets.CACHE_VERSION }}-${{matrix.otp}}-${{matrix.elixir}}-
      - run: mix deps.get
      - uses: actions/cache@v2
        with:
          path: _build/test
          key: compile_test-${{ secrets.CACHE_VERSION }}-${{matrix.otp}}-${{matrix.elixir}}-${{ runner.os }}-${{ hashFiles('mix.lock') }}
          restore-keys: |
            compile_test-${{ secrets.CACHE_VERSION }}-${{matrix.otp}}-${{matrix.elixir}}-${{ runner.os }}-
            compile_test-${{ secrets.CACHE_VERSION }}-${{matrix.otp}}-${{matrix.elixir}}-
      - run: mix deps.compile --skip-umbrella-children
      - run: mix compile --warning-as-errors
      - run: mix coveralls.github --umbrella || mix test
        env:
          DATABASE_PORT: ${{ job.services.postgres.ports[5432] }}

  credo:
    name: Check Credo

    runs-on: ubuntu-latest

    env:
      MIX_ENV: dev

    strategy:
      fail-fast: false
      matrix:
        otp: [24.1.1]
        elixir: [1.12.3]

    steps:
      - uses: actions/checkout@v2
      - uses: erlef/setup-elixir@v1
        with:
          otp-version: ${{matrix.otp}}
          elixir-version: ${{matrix.elixir}}
      - uses: actions/cache@v2
        with:
          path: deps
          key: deps-${{ secrets.CACHE_VERSION }}-${{matrix.otp}}-${{matrix.elixir}}-${{ runner.os }}-${{ hashFiles('mix.lock') }}
          restore-keys: |
            deps-${{ secrets.CACHE_VERSION }}-${{matrix.otp}}-${{matrix.elixir}}-${{ runner.os }}-
            deps-${{ secrets.CACHE_VERSION }}-${{matrix.otp}}-${{matrix.elixir}}-
      - run: mix deps.get
      - uses: actions/cache@v2
        with:
          path: _build/dev
          key: compile_dev-${{ secrets.CACHE_VERSION }}-${{matrix.otp}}-${{matrix.elixir}}-${{ runner.os }}-${{ hashFiles('mix.lock') }}
          restore-keys: |
            compile_dev-${{ secrets.CACHE_VERSION }}-${{matrix.otp}}-${{matrix.elixir}}-${{ runner.os }}-
            compile_dev-${{ secrets.CACHE_VERSION }}-${{matrix.otp}}-${{matrix.elixir}}-
      - run: mix deps.compile --skip-umbrella-children
      - run: mix compile --warning-as-errors
      - run: mix credo --strict

  dialyzer_plt:
    name: Generate Dialyzer PLT

    runs-on: ubuntu-latest

    env:
      MIX_ENV: dev

    strategy:
      fail-fast: false
      matrix:
        otp: [24.1.1]
        elixir: [1.12.3]

    steps:
      - uses: actions/checkout@v2
      - uses: erlef/setup-elixir@v1
        with:
          otp-version: ${{matrix.otp}}
          elixir-version: ${{matrix.elixir}}
      - uses: actions/cache@v2
        with:
          path: deps
          key: deps-${{ secrets.CACHE_VERSION }}-${{matrix.otp}}-${{matrix.elixir}}-${{ runner.os }}-${{ hashFiles('mix.lock') }}
          restore-keys: |
            deps-${{ secrets.CACHE_VERSION }}-${{matrix.otp}}-${{matrix.elixir}}-${{ runner.os }}-
            deps-${{ secrets.CACHE_VERSION }}-${{matrix.otp}}-${{matrix.elixir}}-
      - run: mix deps.get
      - uses: actions/cache@v2
        with:
          path: _build/dev
          key: compile_dev-${{ secrets.CACHE_VERSION }}-${{matrix.otp}}-${{matrix.elixir}}-${{ runner.os }}-${{ hashFiles('mix.lock') }}
          restore-keys: |
            compile_dev-${{ secrets.CACHE_VERSION }}-${{matrix.otp}}-${{matrix.elixir}}-${{ runner.os }}-
            compile_dev-${{ secrets.CACHE_VERSION }}-${{matrix.otp}}-${{matrix.elixir}}-
      - run: mix deps.compile --skip-umbrella-children
      - run: mix compile --warning-as-errors
      - uses: actions/cache@v2
        with:
          path: priv/plts/
          key: dialyzer_plt_dev-${{ secrets.CACHE_VERSION }}-${{matrix.otp}}-${{matrix.elixir}}-${{ runner.os }}-${{ hashFiles('mix.lock') }}
          restore-keys: |
            dialyzer_plt_dev-${{ secrets.CACHE_VERSION }}-${{matrix.otp}}-${{matrix.elixir}}-${{ runner.os }}-
            dialyzer_plt_dev-${{ secrets.CACHE_VERSION }}-${{matrix.otp}}-${{matrix.elixir}}-
      - run: mix dialyzer --plt
      - uses: actions/upload-artifact@v2
        with:
          name: dialyzer_plt_dev-${{matrix.otp}}-${{matrix.elixir}}
          path: priv/plts/

  dialyzer_test:
    name: "Check Dialyzer"

    runs-on: ubuntu-latest

    needs: ['dialyzer_plt']

    env:
      MIX_ENV: dev

    strategy:
      fail-fast: false
      matrix:
        otp: [24.1.1]
        elixir: [1.12.3]

    steps:
      - uses: actions/checkout@v2
      - uses: erlef/setup-elixir@v1
        with:
          otp-version: ${{matrix.otp}}
          elixir-version: ${{matrix.elixir}}
      - uses: actions/cache@v2
        with:
          path: deps
          key: deps-${{ secrets.CACHE_VERSION }}-${{matrix.otp}}-${{matrix.elixir}}-${{ runner.os }}-${{ hashFiles('mix.lock') }}
          restore-keys: |
            deps-${{ secrets.CACHE_VERSION }}-${{matrix.otp}}-${{matrix.elixir}}-${{ runner.os }}-
            deps-${{ secrets.CACHE_VERSION }}-${{matrix.otp}}-${{matrix.elixir}}-
      - run: mix deps.get
      - uses: actions/cache@v2
        with:
          path: _build/dev
          key: compile_dev-${{ secrets.CACHE_VERSION }}-${{matrix.otp}}-${{matrix.elixir}}-${{ runner.os }}-${{ hashFiles('mix.lock') }}
          restore-keys: |
            compile_dev-${{ secrets.CACHE_VERSION }}-${{matrix.otp}}-${{matrix.elixir}}-${{ runner.os }}-
            compile_dev-${{ secrets.CACHE_VERSION }}-${{matrix.otp}}-${{matrix.elixir}}-
      - run: mix deps.compile --skip-umbrella-children
      - run: mix compile --warning-as-errors
      - uses: actions/download-artifact@v2
        with:
          name: dialyzer_plt_dev-${{matrix.otp}}-${{matrix.elixir}}
          path: priv/plts/
      - run: mix dialyzer

  docs:
    name: "Generate Docs"

    runs-on: ubuntu-latest

    env:
      MIX_ENV: docs

    strategy:
      fail-fast: false
      matrix:
        otp: [24.1.1]
        elixir: [1.12.3]

    steps:
      - uses: actions/checkout@v2
      - uses: erlef/setup-elixir@v1
        with:
          otp-version: ${{matrix.otp}}
          elixir-version: ${{matrix.elixir}}
      - uses: actions/cache@v2
        with:
          path: deps
          key: deps-${{ secrets.CACHE_VERSION }}-${{matrix.otp}}-${{matrix.elixir}}-${{ runner.os }}-${{ hashFiles('mix.lock') }}
          restore-keys: |
            deps-${{ secrets.CACHE_VERSION }}-${{matrix.otp}}-${{matrix.elixir}}-${{ runner.os }}-
            deps-${{ secrets.CACHE_VERSION }}-${{matrix.otp}}-${{matrix.elixir}}-
      - run: mix deps.get
      - uses: actions/cache@v2
        with:
          path: _build/dev
          key: compile_dev-${{ secrets.CACHE_VERSION }}-${{matrix.otp}}-${{matrix.elixir}}-${{ runner.os }}-${{ hashFiles('mix.lock') }}
          restore-keys: |
            compile_dev-${{ secrets.CACHE_VERSION }}-${{matrix.otp}}-${{matrix.elixir}}-${{ runner.os }}-
            compile_dev-${{ secrets.CACHE_VERSION }}-${{matrix.otp}}-${{matrix.elixir}}-
      - run: mix deps.compile --skip-umbrella-children
      - run: mix compile --warning-as-errors
      - run: mix docs
      - uses: actions/upload-artifact@v2
        with:
          name: docs
          path: doc
