on:
  workflow_call:
    outputs:
      elixirVersion:
        description: "The .tool-versions Elixir version"
        value: "${{ jobs.detectToolVersions.outputs.elixirVersion }}"
      otpVersion:
        description: "The .tool-versions OTP version"
        value: "${{ jobs.detectToolVersions.outputs.otpVersion }}"

name: "Detect Tool Versions"

jobs:
  detectToolVersions:
    name: "Detect Tool Versions"

    runs-on: ubuntu-latest

    outputs:
      elixirVersion: "${{ steps.toolVersions.outputs.ELIXIR_VERSION }}"
      otpVersion: "${{ steps.toolVersions.outputs.OTP_VERSION }}"

    steps:
      - uses: actions/checkout@v3
      - name: "Read .tool-versions"
        id: toolVersions
        run: |
          ELIXIR_VERSION="$(cat .tool-versions | grep elixir | cut -d' ' -f2- | sed 's/-otp-[0-9]*//')"
          echo Elixir: $ELIXIR_VERSION
          echo ::set-output name=ELIXIR_VERSION::${ELIXIR_VERSION}

          OTP_VERSION="$(cat .tool-versions | grep erlang | cut -d' ' -f2-)"
          echo OTP: $OTP_VERSION
          echo ::set-output name=OTP_VERSION::${OTP_VERSION}
