on:
  pull_request:
    branches:
      - "*"
  workflow_dispatch: {}

name: "Pull Request"

# Secrets:
# * CACHE_VERSION - Set to `date +%s`, set new when the cache should be busted

jobs:
  detectToolVersions:
    name: "Detect Tool Versions"

    uses: ./.github/workflows/part_tool_versioning.yml

  test:
    name: "Test"

    needs: ['detectToolVersions']

    uses: ./.github/workflows/part_test.yml
    with:
      elixirVersion: "${{ needs.detectToolVersions.outputs.elixirVersion }}"
      otpVersion: "${{ needs.detectToolVersions.outputs.otpVersion }}"
    secrets:
      CACHE_VERSION: "${{ secrets.CACHE_VERSION }}"

  docs:
    name: "Docs"

    needs: ['detectToolVersions']

    uses: ./.github/workflows/part_docs.yml
    with:
      elixirVersion: "${{ needs.detectToolVersions.outputs.elixirVersion }}"
      otpVersion: "${{ needs.detectToolVersions.outputs.otpVersion }}"
    secrets:
      CACHE_VERSION: "${{ secrets.CACHE_VERSION }}"

  dependabot:
    name: "Dependabot"

    needs: ['test', 'docs']

    uses: ./.github/workflows/part_dependabot.yml